spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888/
      failFast: true
  application:
    name: client1
  profiles:
    active: cloud
server:
  port: 8001
health:
  config:
    enabled: true