server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thomasandre84/spring-tryouts
          skipSslValidation: true
          basedir: target/config
          default-label: feature(_)init-config-server