spring:
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: git
            uri: https://github.com/thomasandre84/spring-tryouts.git
            skipSslValidation: true
            basedir: target/cloud-config
            default-label: feature/config-clients
            cloneOnStart: true
            timeout: 4
            searchPaths: 'git-config'
            #force-pull: true
            #deleteUntrackedBranches: true
            refreshRate: 60
          - type: native
            uri: file:./native-config



  config:
    name: configserver
server:
  port: 8888